//DelayedDisplay(
//child: TempBackCard(
//temp: data[1]['temp']['day'],
//tempType: data[1]['weather'][0]['main'],
//subtitle: data[1]['weather'][0]['description'],
//date: data[1]['dt'],
//day: '',
//humidity: data[1]['humidity'].toString(),
//comma: "",
//rain: data[1]['clouds'].toString(),
//maxtemp: data[1]['temp']['max'],
//mintemp: data[1]['temp']['min'],
//y1: hour[16]['temp'],
//y2: 23.1,
//y3: 19,
//y4: 25.32,
//y5: 21.3,
//y6: 19.7,
//),
//),
//DelayedDisplay(
//child: TempBackCard(
//temp: data[2]['temp']['eve'],
//tempType: data[2]['weather'][0]['main'],
//subtitle: data[2]['weather'][0]['description'],
//date: data[2]['dt'],
//day: '',
//humidity: data[2]['humidity'].toString(),
//comma: "",
//rain: data[2]['clouds'].toString(),
//maxtemp: data[2]['temp']['max'],
//mintemp: data[2]['temp']['min'],
//y1: 21.7,
//y2: 17.8,
//y3: 24.1,
//y4: 16.5,
//y5: 24.5,
//y6: 15.7,
//),
//),
//DelayedDisplay(
//child: TempBackCard(
//temp: data[3]['temp']['eve'],
//tempType: data[3]['weather'][0]['main'],
//subtitle: data[3]['weather'][0]['description'],
//date: data[3]['dt'],
//day: '',
//humidity: data[3]['humidity'].toString(),
//comma: "",
//rain: data[3]['clouds'].toString(),
//maxtemp: data[3]['temp']['max'],
//mintemp: data[3]['temp']['min'],
//y1: 21.7,
//y2: 17.8,
//y3: 24.1,
//y4: 16.5,
//y5: 24.5,
//y6: 15.7,
//),
//),
//DelayedDisplay(
//child: TempBackCard(
//temp: data[4]['temp']['eve'],
//tempType: data[4]['weather'][0]['main'],
//subtitle: data[4]['weather'][0]['description'],
//date: data[4]['dt'],
//day: '',
//humidity: data[4]['humidity'].toString(),
//comma: "",
//rain: data[4]['clouds'].toString(),
//maxtemp: data[4]['temp']['max'],
//mintemp: data[4]['temp']['min'],
//y1: 21.7,
//y2: 17.8,
//y3: 24.1,
//y4: 16.5,
//y5: 24.5,
//y6: 15.7,
//),
//),
//DelayedDisplay(
//child: TempBackCard(
//temp: data[5]['temp']['eve'],
//tempType: data[5]['weather'][0]['main'],
//subtitle: data[5]['weather'][0]['description'],
//date: data[5]['dt'],
//day: '',
//humidity: data[5]['humidity'].toString(),
//comma: "",
//rain: data[5]['clouds'].toString(),
//maxtemp: data[5]['temp']['max'],
//mintemp: data[5]['temp']['min'],
//y1: 21.7,
//y2: 17.8,
//y3: 24.1,
//y4: 16.5,
//y5: 24.5,
//y6: 15.7,
//),
//),
//DelayedDisplay(
//child: TempBackCard(
//temp: data[6]['temp']['eve'],
//tempType: data[6]['weather'][0]['main'],
//subtitle: data[6]['weather'][0]['description'],
//date: data[6]['dt'],
//day: '',
//humidity: data[6]['humidity'].toString(),
//comma: "",
//rain: data[6]['clouds'].toString(),
//maxtemp: data[6]['temp']['max'],
//mintemp: data[6]['temp']['min'],
//y1: 21.7,
//y2: 17.8,
//y3: 24.1,
//y4: 16.5,
//y5: 24.5,
//y6: 15.7,
//),
//),
//DelayedDisplay(
//child: TempBackCard(
//temp: data[7]['temp']['eve'],
//tempType: data[7]['weather'][0]['main'],
//subtitle: data[7]['weather'][0]['description'],
//date: data[7]['dt'],
//day: '',
//humidity: data[7]['humidity'].toString(),
//comma: "",
//rain: data[7]['clouds'].toString(),
//maxtemp: data[7]['temp']['max'],
//mintemp: data[7]['temp']['min'],
//y1: 21.7,
//y2: 17.8,
//y3: 24.1,
//y4: 16.5,
//y5: 24.5,
//y6: 15.7,
//),
//),